name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Build with uv
        run: uv build

      - name: Publish to PyPI with uv
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
